### ISSUE TITLE
question: set cloudinit manually

### ISSUE THREAD

**Issue by cybercoder** [osism/k8s-capi-images#240]
Is it possible to set cloudinit manually?
I need to set a password and so on.

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
.
.
.
              volumes:
                - name: disk0
                  dataVolume:
                    name: disk0
                - name: cinit
                  cloudInitNoCloud:
                    userData: |-
                      #cloud-config
                      apt:
                        primary:
                          - arches: [default]
                            uri: http://de.archive.ubuntu.com/ubuntu/
                      package_update: true
                      packages:
                        - qemu-guest-agent
                      runcmd:
                        - - systemctl
                          - enable
                          - --now
                          - qemu-guest-agent.service
                      user: myuser
                      password: mypassword
                      ssh_pwauth: True
                      chpasswd:
                        expire: false
```
But it seems it doesn't apply
